// add items to the "Add Items" tab

  var items = [
  {
      "name" : "sofa",
      "image" : "models/thumbnails/sofa.jpg",
      "model" : "models/js/sofa.js",
      "model_img":"models/sofa/sofa.png",
      "type" : "1",
      "itm":"custom",
	  "colour": "grey stained walnut effect",
	  "price" : "$50",
	  "articleno" : "60247409",
	  "width" : "250",
	  "height" : "100",
	  "depth" : "20",
	  "modeltype" : "storage frame"
    },
    {
      "name" : "sink",
      "image" : "models/thumbnails/sink.jpg",
      "model" : "models/js/sink.js",
      "model_img":"models/sink/sink.png",
      "type" : "1",
      "itm":"custom",
	  "colour": "grey stained walnut effect",
	  "price" : "$50",
	  "articleno" : "60247409",
	  "width" : "160",
	  "height" : "130",
	  "depth" : "20",
	  "modeltype" : "storage frame"
    },
    {
      "name" : "oven",
      "image" : "models/thumbnails/oven.jpg",
      "model" : "models/js/sink.js",
      "model_img":"images/oven.png",
      "type" : "1",
      "itm":"custom",
	  "colour": "grey stained walnut effect",
	  "price" : "$50",
	  "articleno" : "60247409",
	  "width" : "80",
	  "height" : "110",
	  "depth" : "20",
	  "modeltype" : "storage frame"
    },
	{
      "name" : "60x20x38 cm",
      "image" : "models/thumbnails/Grey Stained.JPG",
      "model" : "models/js/GreyStained.js",
      "type" : "1",
	  "colour": "grey stained walnut effect",
	  "price" : "$50",
	  "articleno" : "60247409",
	  "width" : "60",
	  "height" : "38",
	  "depth" : "20",
	  "modeltype" : "storage frame"
    },
   {
      "name" : "60x20x38 cm",
      "image" : "models/thumbnails/white.JPG",
      "model" : "models/js/white.js",
      "type" : "1",
	  "colour": "white",
	  "price" : "$50",
	  "articleno" : "00245917",
	  "width" : "60",
	  "height" : "38",
	  "depth" : "20",
	  "modeltype" : "storage frame"
    },
   {
      "name" : "60x20x38 cm",
      "image" : "models/thumbnails/black brwon.JPG",
      "model" : "models/js/blackBrown.js",
      "type" : "1",
	  "colour": "black-brown",
	  "price" : "$50",
	  "articleno" : "60245957",
	  "width" : "60",
	  "height" : "38",
	  "depth" : "20",
	  "modeltype" : "storage frame"
    },
   {
      "name" : "60x20x38 cm",
      "image" : "models/thumbnails/60x20x38 cm.JPG",
      "model" : "models/js/60x20x38.js",
      "type" : "2",
	  "colour": "white stained oak effect",
	  "price" : "$50",
	  "articleno" : "80247408",
	  "width" : "60",
	  "height" : "38",
	  "depth" : "20",
	  "modeltype" : "storage frame"
    },
   {
      "name" : "60x20x38 cm",
      "image" : "models/thumbnails/FR18.jpg",
      "model" : "models/js/FR18.js",
      "type" : "2",
	  "colour": "oak effect",
	  "price" : "$50",
	  "articleno" : "00260875",
	  "width" : "60",
	  "height" : "38",
	  "depth" : "20",
	  "modeltype" : "storage frame"
    },
	{
      "name" : "60x40x128 cm",
      "image" : "models/thumbnails/FR01_white.JPG",
      "model" : "models/js/FR01.js",
      "type" : "1",
	  "colour": "white",
	  "price" : "$75",
	  "articleno" : "40245840",
	  "width" : "60",
	  "height" : "128",
	  "depth" : "40",
	  "modeltype" : "storage frame"
    },
	{
      "name" : "60x40x128 cm",
      "image" : "models/thumbnails/FR01_bb.JPG",
      "model" : "models/js/FR01_bb.js",
      "type" : "1",
	  "colour": "black brown",
	  "price" : "$75",
	  "articleno" : "40245944",
	  "width" : "60",
	  "height" : "128",
	  "depth" : "40",
	  "modeltype" : "storage frame"
    },
	{
      "name" : "60x40x128 cm",
      "image" : "models/thumbnails/FR01_oak.JPG",
      "model" : "models/js/FR01_oak.js",
      "type" : "1",
	  "colour": "oak effect",
	  "price" : "$75",
	  "articleno" : "50260868",
	  "width" : "60",
	  "height" : "128",
	  "depth" : "40",
	  "modeltype" : "storage frame"
    },
	{
      "name" : "120x40x38 cm",
      "image" : "models/thumbnails/10294511.JPG",
      "model" : "#",
      "type" : "1",
	  "colour": "grey stained walnut effect",
	  "price" : "$75",
	  "articleno" : "10294511",
	  "width" : "120",
	  "height" : "38",
	  "depth" : "40",
	  "modeltype" : "tv bench"
    },
	{
      "name" : "120x40x38 cm",
      "image" : "models/thumbnails/70294513.JPG",
      "model" : "#",
      "type" : "1",
	  "colour": "white stained oak effect",
	  "price" : "$75",
	  "articleno" : "70294513",
	  "width" : "120",
	  "height" : "38",
	  "depth" : "40",
	  "modeltype" : "tv bench"
    },
	{
      "name" : "120x40x38 cm",
      "image" : "models/thumbnails/50294509.JPG",
      "model" : "#",
      "type" : "1",
	  "colour": "oak effect",
	  "price" : "$75",
	  "articleno" : "50294509",
	  "width" : "120",
	  "height" : "38",
	  "depth" : "40",
	  "modeltype" : "tv bench"
    },
	{
      "name" : "120x40x38 cm",
      "image" : "models/thumbnails/80294503.JPG",
      "model" : "#",
      "type" : "1",
	  "colour": "white",
	  "price" : "$75",
	  "articleno" : "80294503",
	  "width" : "120",
	  "height" : "38",
	  "depth" : "40",
	  "modeltype" : "tv bench"
    },
	{
      "name" : "120x40x38 cm",
      "image" : "models/thumbnails/90294512.JPG",
      "model" : "#",
      "type" : "1",
	  "colour": "black-brown",
	  "price" : "$75",
	  "articleno" : "90294512",
	  "width" : "120",
	  "height" : "38",
	  "depth" : "40",
	  "modeltype" : "tv bench"
    },
   {
      "name" : "Closed Door",
      "image" : "models/thumbnails/thumbnail_Screen_Shot_2014-10-27_at_8.04.12_PM.png",
      "model" : "models/js/closed-door28x80_baked.js",
      "type" : "7",
	  "colour": "",
	  "price" : "$50",
	  "articleno" : "",
	  "width" : "",
	  "height" : "",
	  "depth" : "",
	  "modeltype" : "propping"
    }, 
    {
      "name" : "Open Door",
      "image" : "models/thumbnails/thumbnail_Screen_Shot_2014-10-27_at_8.22.46_PM.png",
      "model" : "models/js/open_door.js",
      "type" : "7",
	  "colour": "",
	  "price" : "$50",
	  "articleno" : "",
	  "width" : "",
	  "height" : "",
	  "depth" : "",
	  "modeltype" : "propping"
    }, 
    {
      "name" : "Window",
      "image" : "models/thumbnails/thumbnail_window.png",
      "model" : "models/js/whitewindow.js",
      "type" : "3",
	  "colour": "",
	  "price" : "$50",
	  "articleno" : "",
	  "width" : "",
	  "height" : "",
	  "depth" : "",
	  "modeltype" : "propping"
    }, 
    {
      "name" : "Chair",
      "image" : "models/thumbnails/thumbnail_Church-Chair-oak-white_1024x1024.jpg",
      "model" : "models/js/gus-churchchair-whiteoak.js",
      "type" : "1",
	  "colour": "",
	  "price" : "$50",
	  "articleno" : "",
	  "width" : "",
	  "height" : "",
	  "depth" : "",
	  "modeltype" : "propping"
    }, 
    {
      "name" : "Red Chair",
      "image" : "models/thumbnails/thumbnail_tn-orange.png",
      "model" : "models/js/ik-ekero-orange_baked.js",
      "type" : "1",
	  "colour": "",
	  "price" : "$50",
	  "articleno" : "",
	  "width" : "",
	  "height" : "",
	  "depth" : "",
	  "modeltype" : "propping"
    },
    {
      "name" : "Blue Chair",
      "image" : "models/thumbnails/thumbnail_ekero-blue3.png",
      "model" : "models/js/ik-ekero-blue_baked.js",
      "type" : "1",
	  "colour": "",
	  "price" : "$50",
	  "articleno" : "",
	  "width" : "",
	  "height" : "",
	  "depth" : "",
	  "modeltype" : "propping"
    },
    {
      "name" : "Dresser - Dark Wood",
      "image" : "models/thumbnails/thumbnail_matera_dresser_5.png",
      "model" : "models/js/DWR_MATERA_DRESSER2.js",
      "type" : "1",
	  "colour": "",
	  "price" : "$50",
	  "articleno" : "",
	  "width" : "",
	  "height" : "",
	  "depth" : "",
	  "modeltype" : "propping"
    }, 
    {
      "name" : "Dresser - White",
      "image" : "models/thumbnails/thumbnail_img25o.jpg",
      "model" : "models/js/we-narrow6white_baked.js",
      "type" : "1",
	  "colour": "",
	  "price" : "$50",
	  "articleno" : "",
	  "width" : "",
	  "height" : "",
	  "depth" : "",
	  "modeltype" : "propping"
    },  
    {
      "name" : "Bedside table - Shale",
      "image" : "models/thumbnails/thumbnail_Blu-Dot-Shale-Bedside-Table.jpg",
      "model" : "models/js/bd-shalebedside-smoke_baked.js",
      "type" : "1",
	  "colour": "",
	  "price" : "$50",
	  "articleno" : "",
	  "width" : "",
	  "height" : "",
	  "depth" : "",
	  "modeltype" : "propping"
    }, 
    {
      "name" : "Bedside table - White",
      "image" : "models/thumbnails/thumbnail_arch-white-oval-nightstand.jpg",
      "model" : "models/js/cb-archnight-white_baked.js",
      "type" : "1",
	  "colour": "",
	  "price" : "$50",
	  "articleno" : "",
	  "width" : "",
	  "height" : "",
	  "depth" : "",
	  "modeltype" : "propping"
    }, 
    {
      "name" : "Wardrobe - White",
      "image" : "models/thumbnails/thumbnail_TN-ikea-kvikine.png",
      "model" : "models/js/ik-kivine_baked.js",
      "type" : "1",
	  "colour": "",
	  "price" : "$50",
	  "articleno" : "",
	  "width" : "",
	  "height" : "",
	  "depth" : "",
	  "modeltype" : "propping"
    }, 
    {
      "name" : "Full Bed",
      "image" : "models/thumbnails/thumbnail_nordli-bed-frame__0159270_PE315708_S4.JPG",
      "model" : "models/js/ik_nordli_full.js",
      "type" : "1",
	  "colour": "",
	  "price" : "$50",
	  "articleno" : "",
	  "width" : "",
	  "height" : "",
	  "depth" : "",
	  "modeltype" : "propping"
    }, 
    {
      "name" : "Bookshelf",
      "image" : "models/thumbnails/thumbnail_kendall-walnut-bookcase.jpg",
      "model" : "models/js/cb-kendallbookcasewalnut_baked.js",
      "type" : "1",
	  "colour": "",
	  "price" : "$50",
	  "articleno" : "",
	  "width" : "",
	  "height" : "",
	  "depth" : "",
	  "modeltype" : "propping"
    }, 
        {
      "name" : "Media Console - White",
      "image" : "models/thumbnails/thumbnail_clapboard-white-60-media-console-1.jpg",
      "model" : "models/js/cb-clapboard_baked.js",
      "type" : "1",
	  "colour": "",
	  "price" : "$50",
	  "articleno" : "",
	  "width" : "",
	  "height" : "",
	  "depth" : "",
	  "modeltype" : "propping"
    }, 
        {
      "name" : "Media Console - Black",
      "image" : "models/thumbnails/thumbnail_moore-60-media-console-1.jpg",
      "model" : "models/js/cb-moore_baked.js",
      "type" : "1",
	  "colour": "",
	  "price" : "$50",
	  "articleno" : "",
	  "width" : "",
	  "height" : "",
	  "depth" : "",
	  "modeltype" : "propping"
    }, 
       {
      "name" : "Sectional - Olive",
      "image" : "models/thumbnails/thumbnail_img21o.jpg",
      "model" : "models/js/we-crosby2piece-greenbaked.js",
      "type" : "1",
	  "colour": "",
	  "price" : "$50",
	  "articleno" : "",
	  "width" : "",
	  "height" : "",
	  "depth" : "",
	  "modeltype" : "placeholder"
    }, 
    {
      "name" : "Sofa - Grey",
      "image" : "models/thumbnails/thumbnail_rochelle-sofa-3.jpg",
      "model" : "models/js/cb-rochelle-gray_baked.js",
      "type" : "1",
	  "colour": "",
	  "price" : "$50",
	  "articleno" : "",
	  "width" : "",
	  "height" : "",
	  "depth" : "",
	  "modeltype" : "propping"
    }, 
        {
      "name" : "Wooden Trunk",
      "image" : "models/thumbnails/thumbnail_teca-storage-trunk.jpg",
      "model" : "models/js/cb-tecs_baked.js",
      "type" : "1",
	  "colour": "",
	  "price" : "$50",
	  "articleno" : "",
	  "width" : "",
	  "height" : "",
	  "depth" : "",
	  "modeltype" : "propping"
    }, 
        {
      "name" : "Floor Lamp",
      "image" : "models/thumbnails/thumbnail_ore-white.png",
      "model" : "models/js/ore-3legged-white_baked.js",
      "type" : "1",
	  "colour": "",
	  "price" : "$50",
	  "articleno" : "",
	  "width" : "",
	  "height" : "",
	  "depth" : "",
	  "modeltype" : "propping"
    },
    {
      "name" : "Coffee Table - Wood",
      "image" : "models/thumbnails/thumbnail_stockholm-coffee-table__0181245_PE332924_S4.JPG",
      "model" : "models/js/ik-stockholmcoffee-brown.js",
      "type" : "1",
	  "colour": "",
	  "price" : "$50",
	  "articleno" : "",
	  "width" : "",
	  "height" : "",
	  "depth" : "",
	  "modeltype" : "propping"
    }, 
    {
      "name" : "Side Table",
      "image" : "models/thumbnails/thumbnail_Screen_Shot_2014-02-21_at_1.24.58_PM.png",
      "model" : "models/js/GUSossingtonendtable.js",
      "type" : "1",
	  "colour": "",
	  "price" : "$50",
	  "articleno" : "",
	  "width" : "",
	  "height" : "",
	  "depth" : "",
	  "modeltype" : "propping"
    }, 
    {
      "name" : "Dining Table",
      "image" : "models/thumbnails/thumbnail_scholar-dining-table.jpg",
      "model" : "models/js/cb-scholartable_baked.js",
      "type" : "1",
	  "colour": "",
	  "price" : "$50",
	  "articleno" : "",
	  "width" : "",
	  "height" : "",
	  "depth" : "",
	  "modeltype" : "propping"
    }, 
    {
      "name" : "Dining table",
      "image" : "models/thumbnails/thumbnail_Screen_Shot_2014-01-28_at_6.49.33_PM.png",
      "model" : "models/js/BlakeAvenuejoshuatreecheftable.js",
      "type" : "1",
	  "colour": "",
	  "price" : "$50",
	  "articleno" : "",
	  "width" : "",
	  "height" : "",
	  "depth" : "",
	  "modeltype" : "propping"
    },
    {
      "name" : "Blue Rug",
      "image" : "models/thumbnails/thumbnail_cb-blue-block60x96.png",
      "model" : "models/js/cb-blue-block-60x96.js",
      "type" : "8",
	  "colour": "",
	  "price" : "$50",
	  "articleno" : "",
	  "width" : "",
	  "height" : "",
	  "depth" : "",
	  "modeltype" : "placeholder"
    },
    {
      "name" : "NYC Poster",
      "image" : "models/thumbnails/thumbnail_nyc2.jpg",
      "model" : "models/js/nyc-poster2.js",
      "type" : "2",
	  "colour": "",
	  "price" : "$50",
	  "articleno" : "",
	  "width" : "",
	  "height" : "",
	  "depth" : "",
	  "modeltype" : "placeholder"
    }
	
   /*     
   {
      "name" : "",
      "image" : "",
      "model" : "",
      "type" : "1"
    }, 
    */
  ];
   
  /*var itemsDiv = $("#items-wrapper")
  for (var i = 0; i < items.length; i++) {
    var item = items[i];
    var html = '<div class="col-xs-6 img_ht">' +
                '<a class="thumbnail add-item" model-name="' + 
                item.name + 
                '" model-url="' +
                item.model +
                '" model-type="' +
                item.type + 
                '"><img src="' +
                item.image + 
                '" alt="Add Item"> '+
                item.name +
                '</a></div>';
    itemsDiv.append(html);
  }*/ 
